FROM apache/spark:3.5.6

USER root

WORKDIR /app

COPY ./jobs ./jobs
COPY ./models ./models
COPY ./utils ./utils
COPY ./model_registry.json ./model_registry.json
COPY ./requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt
