FROM python:3.12-slim

WORKDIR /app

COPY ./simulator ./simulator
COPY ./jobs ./jobs
COPY ./models ./models
COPY ./utils ./utils
COPY ./model_registry.json ./model_registry.json
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt