version: '3.8'

networks:
  kafka-net:
    driver: bridge

volumes:
  postgres_data:

services:

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: streaming_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "streaming_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro #:ro stands for read only, so that container can not modify or delete
    networks:
      - kafka-net

  kafka1:
    image: confluentinc/cp-kafka:7.8.0
    container_name: kafka1
    hostname: kafka1
    restart: always
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD","kafka-broker-api-versions","--bootstrap-server","localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
      #need start_period so that Docker don't mark the broker as "Unhealthy" because kafka takes longer to start than many services
      start_period: 30s

    environment:
      CLUSTER_ID: EmptNWtoR4GGWx-BH6nGLQ

      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093

      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:29092,EXTERNAL://localhost:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093

      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    volumes:
      - ./kafka1/data:/var/lib/kafka/data

    networks:
      - kafka-net

  kafka2:
    image: confluentinc/cp-kafka:7.8.0
    container_name: kafka2
    hostname: kafka2
    restart: always
    ports:
      - "9094:9092"
    healthcheck:
      test: ["CMD","kafka-broker-api-versions","--bootstrap-server","localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
      #need start_period so that Docker don't mark the broker as "Unhealthy" because kafka takes longer to start than many services
      start_period: 30s
    environment:
      CLUSTER_ID: EmptNWtoR4GGWx-BH6nGLQ

      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093

      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:29092,EXTERNAL://localhost:9094

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093

      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    volumes:
      - ./kafka2/data:/var/lib/kafka/data

    networks:
      - kafka-net

  kafka3:
    image: confluentinc/cp-kafka:7.8.0
    container_name: kafka3
    hostname: kafka3
    restart: always
    ports:
      - "9096:9092"
    healthcheck:
      test: ["CMD","kafka-broker-api-versions","--bootstrap-server","localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
      #need start_period so that Docker don't mark the broker as "Unhealthy" because kafka takes longer to start than many services
      start_period: 30s
    environment:
      CLUSTER_ID: EmptNWtoR4GGWx-BH6nGLQ

      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093

      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:29092,EXTERNAL://localhost:9096

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093

      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    volumes:
      - ./kafka3/data:/var/lib/kafka/data

    networks:
      - kafka-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    ports:
      - "8080:8080"

    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:29092,kafka2:29092,kafka3:29092

    depends_on:
      - kafka1
      - kafka2
      - kafka3

    networks:
      - kafka-net

  topic_init:
    image: confluentinc/cp-kafka:7.8.0
    container_name: topic_init
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    command: >
      bash -c "
        while ! kafka-topics --list --bootstrap-server kafka1:29092 > /dev/null 2>&1;
        do
          sleep 2
        done

        kafka-topics --create --if-not-exists --topic market-features --bootstrap-server kafka1:29092 --partitions 1 --replication-factor 3
        kafka-topics --create --if-not-exists --topic market-labels --bootstrap-server kafka1:29092 --partitions 1 --replication-factor 3
      "
    networks:
      - kafka-net

  features_producer: #service name, container name are used for diffrent purposes.
    build:
      context: .
      dockerfile: Dockerfile.python
    image: python_image # for creating image with custom name, otherwise <projectName_serviceName_1> by default
    container_name: features_producer
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      topic_init:
        condition: service_completed_successfully
    command: python /app/simulator/features_producer.py
    volumes:
      - ./simulator:/app/simulator
      - ./data/elec2_real_time_features.csv:/app/data/elec2_real_time_features.csv
    networks:
      - kafka-net

  labels_producer:
    build:
      context: .
      dockerfile: Dockerfile.python
    image: python_image
    container_name: labels_producer
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      topic_init:
        condition: service_completed_successfully
    command: python /app/simulator/labels_producer.py
    volumes:
      - ./data/elec2_true_labels.csv:/app/data/elec2_true_labels.csv
      - ./simulator/labels_producer.py:/app/simulator/labels_producer.py
    networks:
      - kafka-net

  streaming_prediction:
    build:
      context: .
      dockerfile: Dockerfile.spark
    image: spark_image
    container_name: streaming_prediction
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      topic_init:
        condition: service_completed_successfully
    environment:
      PYTHONPATH: /app
    command:
      - /opt/spark/bin/spark-submit
      - --conf
      - spark.jars.ivy=/tmp/.ivy2
      - --packages # --packages is used to downloads external jars
      - org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.6,org.postgresql:postgresql:42.7.4
      - /app/jobs/streaming_predictions.py
      #kafka connector and jdbc driver because this spark job is reading from kafka and writing to postgres
    volumes:
      - ./jobs:/app/jobs
      - ./models:/app/models
      - ./utils:/app/utils
      - ./checkpoints/streaming_prediction:/tmp/checkpoints/streaming_prediction
    networks:
      - kafka-net

  train_model:
    profiles:
      - training
    build:
      context: .
      dockerfile: Dockerfile.spark
    image: spark_image
    container_name: train_model
    environment:
      PYTHONPATH: /app
    command:
      - /opt/spark/bin/spark-submit
      - /app/jobs/train_model.py
    volumes:
      - ./utils:/app/utils
      - ./jobs:/app/jobs
      - ./data:/app/data
      - ./models:/app/models
    networks:
      - kafka-net

  feature_monitor:
    build:
      context: .
      dockerfile: Dockerfile.spark
    image: spark_image
    container_name: feature_monitor
    restart: always
    environment:
      PYTHONPATH: /app # similar to using sys.path.append() or sys.path.insert() directly in the code file
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      topic_init:
        condition: service_completed_successfully
    command:
      - /opt/spark/bin/spark-submit
      - --conf
      - spark.jars.ivy=/tmp/.ivy2
      - --packages
      - org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.6
      - /app/jobs/feature_monitor.py
    volumes:
      - ./utils:/app/utils
      - ./jobs:/app/jobs
    networks:
      - kafka-net

  performance_monitor:
    build:
      context: .
      dockerfile: Dockerfile.spark
    image: spark_image
    container_name: performance_monitor
    restart: always
    environment:
      PYTHONPATH: /app
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      topic_init:
        condition: service_completed_successfully
    command:
      - /opt/spark/bin/spark-submit
      - --conf
      - spark.jars.ivy=/tmp/.ivy2
      - --packages
      - org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.6,org.postgresql:postgresql:42.7.4
      - /app/jobs/performance_monitor.py
    volumes:
      - ./utils:/app/utils
      - ./jobs:/app/jobs
      - ./models:/app/models
      - ./model_registry.json:/app/model_registry.json
    networks:
      - kafka-net
    